#默认环境配置
spring:
  profiles:
    active: default

#开发环境配置
spring:
    profiles: default
    name: 开发环境
    mailTo: 741919791@qq.com
    datasource:
        name: test
#        url: jdbc:mysql://127.0.0.1:3306/hktest?characterEncoding=utf8&useSSL=false
#        username: root
#        password:
        url: jdbc:mysql://10.0.0.214:56688/homework?characterEncoding=utf8&useSSL=false
        username: caiji
        password: caiji1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
server:
    port: 9084
cbp_host: http://10.0.0.214:8080/cbp/


---

#测试环境配置
spring:
    profiles: test
    name: 测试环境
    mailTo: 741919791@qq.com,550425613@qq.com
    datasource:
        name: test
        url: jdbc:mysql://rm-wz95c58i9ixyqw206.mysql.rds.aliyuncs.com:3306/cjhms?characterEncoding=utf8&useSSL=false
        username: cjyun
        password: cjyun-TEST
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
server:
    port: 9084
cbp_host: http://test-cjyun-api.ecaicn.com/cbp/

---

#本地环境配置
spring:
    profiles: local
    name: 本地环境
    mailTo: 741919791@qq.com
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/homework?characterEncoding=utf8&useSSL=false
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
server:
    port: 9084
cbp_host: http://10.0.0.214:8080/cbp/

